[package]
name = "green/vluxyai"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

authors = ["Viper <greenviper126@gmail.com>"]
private = true

[server-dependencies]

#main:

#optional:


[dev-dependencies]

#main:

#optional:


[dependencies]

#main:
trove = "sleitnick/trove@1.5.0"
dash = "dev-alastair/dash@1.1.2" #for tables / has intellisense
promise = "evaera/promise@4.0.0" #for some bug prevention

#optional:
